FrontEndWebsite/FrontEndMVC/Controllers/StudentSelectController.cs
using CoreLib.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Security.Claims;

namespace FrontEndMVC.Controllers
{
    [Authorize(Roles = "Student")]
    public class StudentSelectController : Controller
    {
        private IStudentSelect _studentSelect;

        public StudentSelectController(IStudentSelect studentSelect)
        {       
            _studentSelect = studentSelect;
        }

        [HttpPost]
        public IActionResult Index(string courseID)
        {
            var userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            courseID = courseID.Substring(2);
            var result = _studentSelect.CreateStudentSelect(courseID, userID);
            if (result)
            { 
                return RedirectToAction("Index", "Course");
            }

            //duplicated stuselect
            TempData["stuselect"] = "duplicated";
            return RedirectToAction("Index", "Course");
        }

        [HttpGet]
        public IActionResult Index()
        {
            var userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var result = _studentSelect.ShowAllStuSelect(userID);
            return View(result.ToList());
        }

        [HttpPost]
        public IActionResult DeleteSelect(string rowSelectID)
        {
            var userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var result = _studentSelect.DeletRowData(rowSelectID);
            if (result)
                return View("Index", _studentSelect.ShowAllStuSelect(userID).ToList());
            else
                return RedirectToAction("Index", "Course");
        }
    }
}

FrontEndWebsite/FrontEndMVC/Views/StudentSelect/Index.cshtml
@using CoreLib.ClientViewModel;
@model List<StudentSelectModel>;
@{
    ViewData["Title"] = "Index";
}

<br />
<div class="bd-callout" style="margin-bottom: 50px">
	<h3> <strong>My Course Selection</strong> </h3>
</div>

<div class="card" style="background: wheat;">
    <table class="table table-striped table-secondary">
      <thead>
        <tr>
          <th scope="col"> </th>
          <th scope="col">Course</th>
          <th scope="col">Teacher</th>
          <th scope="col">Hour</th>
          <th scope="col">StartDate</th>
          <th scope="col">EndDate</th>
          <th scope="col">Location</th>
          <th scope="col"> </th>
        </tr>
      </thead>
      <tbody>
            @if (Model.Count > 0)
            { 
                for (int i = 0; i <Model.Count; i++)
                {
                    <form asp-action="DeleteSelect" asp-controller="StudentSelect" method="post" id="DeleteForm">
                        <input type="hidden" name="rowSelectID" value="@Model[i].Id.ToString()"/>
                        <tr>
                            <th scope="row">@(i+1)</th>
                            <td>@Model[i].CourseName</td>
                            <td>@Model[i].TeacherName</td>
                            <td>@Model[i].Hour</td>
                            <td>@Model[i].sDate</td>
                            <td>@Model[i].eDate</td>
                            <td>@Model[i].Loaction</td>
                        <td> <button class="btn btn-danger" name="@Model[i].Id.ToString()" type="submit"> Delete </button> </td>
                        </tr>
                    </form>
                }          
            }
        </tbody>>
    </table>
    @if (Model.Count == 0)
    {
        <h4 style="align-items: center; color: red;"> No Course </h4>
    }
</div>